#!/usr/bin/env python3
"""
SEO Verification Audit — geometrylite.poki2.online
Run from repo root: python3 scripts/seo_verify.py
Outputs a Markdown report to docs/seo-audit-report.md
"""
import re, os, sys, html
from datetime import date

DOMAIN = open('.domain').read().strip()
TODAY = date.today().isoformat()

GAME_PAGES = [
    'index.html', 'egg-dash.html', 'wave-dash.html',
    'geometry-lite-classic.html', 'geometry-jump.html',
    'geometry-game-3d.html', 'spooky-dash.html',
    'tap-road-beat.html', 'xmas-dash.html',
]
ALL_PAGES = [f for f in os.listdir('.') if f.endswith('.html')]
ALL_PAGES.sort()

def extract(content, pattern, group=1, default='—'):
    m = re.search(pattern, content)
    return m.group(group) if m else default

def check(content, pattern):
    return '✅' if re.search(pattern, content) else '❌'

results = []
warnings = []

# ── Per-page checks ─────────────────────────────────────────────────────────
page_rows = []
for filename in ALL_PAGES:
    c = open(filename, encoding='utf-8').read()

    canonical   = check(c, rf'href="https://{re.escape(DOMAIN)}')
    og_title    = check(c, r'property="og:title"')
    og_desc     = check(c, r'property="og:description"')
    og_img      = check(c, r'property="og:image"')
    og_url      = check(c, rf'property="og:url" content="https://{re.escape(DOMAIN)}')
    tw_card     = check(c, r'name="twitter:card"')
    schema      = check(c, r'"@type":"VideoGame"')
    ga          = check(c, r'G-KKVKM3C6FM')
    cwv         = check(c, r'metric_id')

    # Detect leftover share modal with github.io URL (must be in the value= attribute)
    stale_share = '⚠️' if re.search(r'share_link_input[^>]*value="https://geometrylite\.github\.io', c) else '✅'
    # Detect stale domain ONLY in SEO-critical tags (canonical, og:url, og:type, title)
    seo_tags = ' '.join(re.findall(r'<(?:link|meta)[^>]*(?:canonical|og:url|og:type|og:title)[^>]*>', c))
    stale_dom = '⚠️' if 'github.io' in seo_tags else '✅'

    page_rows.append(
        f'| {filename} | {canonical} | {og_title} | {og_desc} | {og_img} | {og_url} | {tw_card} | {schema} | {ga} | {cwv} | {stale_share} | {stale_dom} |'
    )

    if '❌' in [canonical, og_title, og_desc, og_img, og_url, tw_card, ga]:
        warnings.append(f'- **{filename}**: missing one or more required tags')
    if schema == '❌' and filename in GAME_PAGES:
        warnings.append(f'- **{filename}**: GAME PAGE missing VideoGame schema')

# ── robots.txt ───────────────────────────────────────────────────────────────
robots = open('robots.txt').read() if os.path.exists('robots.txt') else ''
robots_ok       = '✅' if 'User-agent: *' in robots else '❌'
robots_disallow = '✅' if 'Disallow: /embed/' in robots else '❌'
robots_sitemap  = '✅' if f'Sitemap: https://{DOMAIN}/sitemap.xml' in robots else '❌'

# ── sitemap.xml ──────────────────────────────────────────────────────────────
sitemap = open('sitemap.xml').read() if os.path.exists('sitemap.xml') else ''
sitemap_urls = re.findall(r'<loc>(.*?)</loc>', sitemap)
sitemap_count = len(sitemap_urls)
sitemap_domain_ok = '✅' if all(f'https://{DOMAIN}' in u for u in sitemap_urls) else '❌'
sitemap_has_all = '✅' if sitemap_count >= 15 else f'⚠️ only {sitemap_count} URLs'

# ── Internal link check ───────────────────────────────────────────────────────
internal_links = {}
broken_links = []
page_slugs = set()
for f in ALL_PAGES:
    slug = '/' + f.replace('.html', '')
    page_slugs.add(slug)
    page_slugs.add('/' + f)
page_slugs.add('/')

for filename in ALL_PAGES:
    c = open(filename, encoding='utf-8').read()
    hrefs = re.findall(r'href="(/[^"#?]*)"', c)
    for href in hrefs:
        # Normalise
        slug = href if href != '/' else '/'
        slug_html = slug.lstrip('/') + '.html'
        if slug in page_slugs or slug_html in ALL_PAGES or os.path.exists(slug.lstrip('/')) or slug.startswith('/resources') or slug.startswith('/embed') or slug.startswith('/data'):
            continue  # known good
        broken_links.append(f'  - `{filename}` → `{href}`')

broken_links = sorted(set(broken_links))

# ── GA presence summary ───────────────────────────────────────────────────────
ga_missing = [f for f in ALL_PAGES if 'G-KKVKM3C6FM' not in open(f, encoding='utf-8').read()]

# ── Build report ─────────────────────────────────────────────────────────────
sep = '\n'
report = f"""# SEO Verification Audit Report
**Site:** https://{DOMAIN}  
**Date:** {TODAY}  
**Generated by:** `scripts/seo_verify.py`

---

## 1. robots.txt

| Check | Status |
|---|---|
| File exists | {'✅' if os.path.exists('robots.txt') else '❌'} |
| User-agent: * | {robots_ok} |
| Disallow: /embed/ | {robots_disallow} |
| Sitemap URL correct | {robots_sitemap} |

## 2. sitemap.xml

| Check | Status |
|---|---|
| File exists | {'✅' if os.path.exists('sitemap.xml') else '❌'} |
| All URLs use correct domain | {sitemap_domain_ok} |
| URL count (target ≥ 15) | {sitemap_has_all} |

**URLs in sitemap ({sitemap_count}):**
{sep.join('- ' + u for u in sitemap_urls)}

## 3. Per-Page SEO Tags

| Page | canonical | og:title | og:desc | og:image | og:url (domain) | twitter:card | VideoGame schema | GA4 | CWV | share URL | stale domain |
|---|---|---|---|---|---|---|---|---|---|---|---|
{sep.join(page_rows)}

**Legend:** ✅ present/correct  ❌ missing  ⚠️ issue detected

## 4. Internal Link Audit

{('**No broken internal links detected ✅**') if not broken_links else ('**Potentially broken internal links:**' + sep + sep.join(broken_links))}

## 5. Google Analytics Coverage

{'**GA4 tag present on all pages ✅**' if not ga_missing else ('**Pages MISSING GA4 tag:**' + sep + sep.join('- ' + f for f in ga_missing))}

## 6. Warnings & Action Items

{sep.join(warnings) if warnings else '**No critical issues found ✅**'}

## 7. Manual Verification Checklist

| Task | How | Status |
|---|---|---|
| Check Google indexing | `site:{DOMAIN}` in Google Search | ❌ Manual |
| GSC Performance (rankings) | [GSC → Performance](https://search.google.com/search-console) | ❌ Manual |
| PageSpeed Insights | [pagespeed.web.dev](https://pagespeed.web.dev/?url=https%3A%2F%2F{DOMAIN}) | ❌ Manual |
| Mobile-Friendly Test | [search.google.com/test/mobile-friendly](https://search.google.com/test/mobile-friendly?url=https%3A%2F%2F{DOMAIN}) | ❌ Manual |
| Rich Results Test | [search.google.com/test/rich-results](https://search.google.com/test/rich-results?url=https%3A%2F%2F{DOMAIN}) | ❌ Manual |
| Backlink count | GSC → Links → External | ❌ Manual |
| Core Web Vitals (field data) | GSC → Core Web Vitals report | ❌ Manual |
| Submit sitemap to GSC | GSC → Sitemaps → `https://{DOMAIN}/sitemap.xml` | ❌ Manual |
"""

os.makedirs('docs', exist_ok=True)
with open('docs/seo-audit-report.md', 'w', encoding='utf-8') as f:
    f.write(report)

print(report)
print(f"\nReport saved to: docs/seo-audit-report.md")
